import app from '../src/app';
import http from 'http';
import fs from 'fs';
import path from 'path';

async function runLiveIntegrationTest() {
  console.log('====================================================');
  console.log('🚀 PAIDI END-TO-END SYSTEM INTEGRATION SUITE (8/8)');
  console.log('====================================================\n');

  // Start test server on ephemeral port 3009
  const PORT = 3009;
  const server = http.createServer(app);

  await new Promise<void>((resolve) => {
    server.listen(PORT, () => {
      console.log(`📡 Test Server listening on http://localhost:${PORT}`);
      resolve();
    });
  });

  try {
    // 1. Test Health Endpoint
    console.log('\n[1] Checking /health status...');
    const healthRes = await fetch(`http://localhost:${PORT}/health`);
    const healthData = await healthRes.json();
    console.log(`  Status: ${healthRes.status} | Service: ${healthData.service}`);
    if (healthRes.status !== 200 || healthData.status !== 'ok') {
      throw new Error('Health check failed');
    }
    console.log('  ✅ PASSED: Health endpoint active and secured.');

    // 2. Test User Registration & Authentication
    console.log('\n[2] Authenticating User Session...');
    const authRes = await fetch(`http://localhost:${PORT}/api/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email: 'admin@paidi.enterprise',
        password: 'PaidiEnterprise2026!Secure'
      })
    });
    const authData = await authRes.json();
    if (!authRes.ok || !authData.token) {
      throw new Error(`Authentication failed: ${JSON.stringify(authData)}`);
    }
    const token = authData.token;
    console.log(`  Token: ${token.substring(0, 20)}... (Role: ${authData.user.role})`);
    console.log('  ✅ PASSED: User session verified and JWT issued.');

    // 3. Test Document Ingestion via Multipart Form Data & Executive Summary
    console.log('\n[3] Testing Document Upload & Executive Summarizer...');
    const boundary = '----WebKitFormBoundaryPAIDI' + Date.now();
    const testDocContent = `
# PAIDI AIR-GAPPED VECTOR SECURITY DIRECTIVE

Section 1: Private Vector Clustering
All embedding vectors generated by the PAIDI platform remain strictly local. 
Under no circumstances are document vectors or tokenized chunks transmitted to external third-party model providers.
Capital budget for 2026 reached $14.2 Million with 99.8% precision guarantee.
`;
    const bodyParts = [
      `--${boundary}`,
      'Content-Disposition: form-data; name="file"; filename="airgap-policy.txt"',
      'Content-Type: text/plain',
      '',
      testDocContent.trim(),
      `--${boundary}--`,
      ''
    ].join('\r\n');

    const uploadRes = await fetch(`http://localhost:${PORT}/api/documents/upload`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': `multipart/form-data; boundary=${boundary}`
      },
      body: bodyParts
    });

    const uploadData = await uploadRes.json();
    if (!uploadRes.ok || !uploadData.document) {
      throw new Error(`Upload failed: ${JSON.stringify(uploadData)}`);
    }
    const docId1 = uploadData.document.id;
    console.log(`  Document: "${uploadData.document.filename}" | Chunks: ${uploadData.document.totalChunks}`);
    console.log(`  Executive Summary: "${uploadData.document.summary?.bullets?.[0] || 'Generated'}"`);
    console.log('  ✅ PASSED: Document ingested, chunked, and summarized.');

    // 4. Test RAG Query with Citation Grounding
    console.log('\n[4] Testing Grounded RAG Query with Verifiable Citations...');
    const query = "Are document vectors transmitted to external providers?";
    const queryRes = await fetch(`http://localhost:${PORT}/api/chat/query`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ query })
    });

    const queryData = await queryRes.json();
    if (!queryRes.ok || !queryData.answer) {
      throw new Error(`RAG Query failed: ${JSON.stringify(queryData)}`);
    }

    console.log(`  Question: "${query}"`);
    console.log(`  Answer: "${queryData.answer.substring(0, 90)}..."`);
    console.log(`  Confidence: ${(queryData.confidence * 100).toFixed(0)}%`);
    console.log(`  Citations: ${queryData.citations.length} verified citation(s)`);
    console.log('  ✅ PASSED: RAG query generated grounded answer with citations.');

    // 5. Test SSE Streaming Pipeline
    console.log('\n[5] Testing Real-Time SSE Token Streaming Pipeline...');
    const streamRes = await fetch(`http://localhost:${PORT}/api/chat/stream`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ query: 'Explain vector clustering' })
    });
    const streamText = await streamRes.text();
    if (!streamRes.ok || !streamText.includes('event: token')) {
      throw new Error('Streaming failed');
    }
    console.log('  ✅ PASSED: Server-Sent Events stream delivered token chunks.');

    // 6. Test Comparative Multi-Document RAG
    console.log('\n[6] Testing Comparative Document Delta Analysis...');
    const compRes = await fetch(`http://localhost:${PORT}/api/chat/compare`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        documentId1: docId1,
        documentId2: docId1,
        topic: 'vector clustering',
      })
    });
    const compData = await compRes.json();
    if (!compRes.ok || !compData.comparison) {
      throw new Error('Document comparison failed');
    }
    console.log('  ✅ PASSED: Multi-document comparative analysis synthesized.');

    // 7. Test Cryptographic Audit Export (CSV & JSON)
    console.log('\n[7] Testing Cryptographic Audit Export (CSV)...');
    const auditRes = await fetch(`http://localhost:${PORT}/api/audit/export?format=csv`, {
      headers: { 'Authorization': `Bearer ${token}` }
    });
    const csvData = await auditRes.text();
    if (!auditRes.ok || !csvData.includes('Action')) {
      throw new Error('Audit export failed');
    }
    console.log('  ✅ PASSED: Cryptographic audit log exported in CSV.');

    // 8. Test RAG Triad Evaluation Telemetry
    console.log('\n[8] Testing Real-Time RAG Triad Evaluation Telemetry...');
    const evalRes = await fetch(`http://localhost:${PORT}/api/evaluation/metrics`, {
      headers: { 'Authorization': `Bearer ${token}` }
    });
    const evalData = await evalRes.json();
    if (!evalRes.ok || !evalData.summary) {
      throw new Error('Evaluation metrics failed');
    }
    console.log(`  Faithfulness: ${evalData.summary.faithfulness}% | Relevance: ${evalData.summary.answerRelevance}% | Precision: ${evalData.summary.contextPrecision}%`);
    console.log('  ✅ PASSED: RAG Triad benchmarks aggregated successfully.');

    console.log('\n====================================================');
    console.log('🎉 ALL 8/8 END-TO-END INTEGRATION TESTS PASSED!');
    console.log('====================================================');
  } finally {
    server.close();
  }
}

runLiveIntegrationTest().catch(err => {
  console.error('❌ Integration Test Failed:', err);
  process.exit(1);
});
