import app from '../src/app';
import http from 'http';
import fs from 'fs';
import path from 'path';

async function runLiveIntegrationTest() {
  console.log('====================================================');
  console.log('🚀 PAIDI END-TO-END SYSTEM INTEGRATION TEST');
  console.log('====================================================\n');

  // Start test server on ephemeral port 3009
  const PORT = 3009;
  const server = http.createServer(app);

  await new Promise<void>((resolve) => {
    server.listen(PORT, () => {
      console.log(`📡 Test Server listening on http://localhost:${PORT}`);
      resolve();
    });
  });

  try {
    // 1. Test Health Endpoint
    console.log('\n[1] Checking /health status...');
    const healthRes = await fetch(`http://localhost:${PORT}/health`);
    const healthData = await healthRes.json();
    console.log(`  Status: ${healthRes.status} | Service: ${healthData.service}`);
    if (healthRes.status !== 200 || healthData.status !== 'ok') {
      throw new Error('Health check failed');
    }
    console.log('  ✅ PASSED: Health endpoint active and secured.');

    // 2. Test User Registration & Authentication
    console.log('\n[2] Authenticating User Session...');
    const authRes = await fetch(`http://localhost:${PORT}/api/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email: 'admin@paidi.enterprise',
        password: 'PaidiEnterprise2026!Secure'
      })
    });
    const authData = await authRes.json();
    if (!authRes.ok || !authData.token) {
      throw new Error(`Authentication failed: ${JSON.stringify(authData)}`);
    }
    const token = authData.token;
    console.log(`  Token: ${token.substring(0, 20)}... (Role: ${authData.user.role})`);
    console.log('  ✅ PASSED: User session verified and JWT issued.');

    // 3. Test Document Ingestion via Multipart Form Data
    console.log('\n[3] Testing Document Upload & Semantic Ingestion...');
    const boundary = '----WebKitFormBoundaryPAIDI' + Date.now();
    const testDocContent = `
# PAIDI AIR-GAPPED VECTOR SECURITY DIRECTIVE

Section 1: Private Vector Clustering
All embedding vectors generated by the PAIDI platform remain strictly local. 
Under no circumstances are document vectors or tokenized chunks transmitted to external third-party model providers.
`;
    const bodyParts = [
      `--${boundary}`,
      'Content-Disposition: form-data; name="file"; filename="airgap-policy.txt"',
      'Content-Type: text/plain',
      '',
      testDocContent.trim(),
      `--${boundary}--`,
      ''
    ].join('\r\n');

    const uploadRes = await fetch(`http://localhost:${PORT}/api/documents/upload`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': `multipart/form-data; boundary=${boundary}`
      },
      body: bodyParts
    });

    const uploadData = await uploadRes.json();
    if (!uploadRes.ok || !uploadData.document) {
      throw new Error(`Upload failed: ${JSON.stringify(uploadData)}`);
    }
    console.log(`  Document: "${uploadData.document.filename}" | Chunks: ${uploadData.document.totalChunks}`);
    console.log('  ✅ PASSED: Document ingested, chunked, and vector indexed.');

    // 4. Test RAG Query with Citation Grounding
    console.log('\n[4] Testing Grounded RAG Query with Verifiable Citations...');
    const query = "Are document vectors transmitted to external providers?";
    const queryRes = await fetch(`http://localhost:${PORT}/api/chat/query`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ query })
    });

    const queryData = await queryRes.json();
    if (!queryRes.ok || !queryData.answer) {
      throw new Error(`RAG Query failed: ${JSON.stringify(queryData)}`);
    }

    console.log(`  Question: "${query}"`);
    console.log(`  Answer: "${queryData.answer.substring(0, 120)}..."`);
    console.log(`  Confidence: ${(queryData.confidence * 100).toFixed(0)}%`);
    console.log(`  Citations: ${queryData.citations.length} verified citation(s)`);
    if (queryData.citations.length > 0) {
      console.log(`    [Citation 1] ${queryData.citations[0].filename} (Page ${queryData.citations[0].pageNumber}) - ${queryData.citations[0].relevanceScore}%`);
    }
    console.log('  ✅ PASSED: RAG query generated grounded answer with citations.');

    // 5. Test History / Telemetry Retrieval
    console.log('\n[5] Testing Audit History & Telemetry...');
    const histRes = await fetch(`http://localhost:${PORT}/api/chat/history`, {
      headers: { 'Authorization': `Bearer ${token}` }
    });
    const histData = await histRes.json();
    console.log(`  Total Logged Queries: ${histData.total}`);
    if (histData.total < 1) throw new Error('Query was not recorded in history');
    console.log('  ✅ PASSED: Query audit and telemetry successfully persisted.');

    console.log('\n====================================================');
    console.log('🎉 ALL 5/5 END-TO-END INTEGRATION TESTS PASSED!');
    console.log('====================================================');
  } finally {
    server.close();
  }
}

runLiveIntegrationTest().catch(err => {
  console.error('❌ Integration Test Failed:', err);
  process.exit(1);
});
